<?php
return array(
    "automaker"=>array(
        "connectionString"=>"mysql:host=localhost;dbname=automaker",
        "username"=>"root",
        "password"=>"",
        "charset"=>"utf8"
    ),
    "sakila"=>array(
        "connectionString"=>"mysql:host=localhost;dbname=sakila",
        "username"=>"root",
        "password"=>"",
        "charset"=>"utf8"
    ),
    "world"=>array(
        "connectionString"=>"mysql:host=localhost;dbname=world",
        "username"=>"root",
        "password"=>"",
        "charset"=>"utf8"
    ),    
);